apiVersion: "kapitan.razee.io/v1alpha1"
kind: RemoteResource
metadata:
  name: hello-app
  namespace: default
spec:
  requests:
    - options:
        url: https://raw.githubusercontent.com/kitch-razee/hello-app/master/hello-deployment.yaml
